version: "3"

services:
  ghost:
    image: ghost:alpine
    restart: unless-stopped
    environment:
      - NODE_ENV
    volumes:
      - ./ghost/content:/var/lib/ghost/content
      - ./ghost/config.production.json:/var/lib/ghost/config.production.json
      - ./ghost/config.development.json:/var/lib/ghost/config.development.json

  isso:
    build:
      context: ./isso
      dockerfile: Dockerfile
      args:
        - ISSO_HOST=${ISSO_HOST}
        - ISSO_PORT=${ISSO_PORT}
        - SMTP_USER_NAME=${SMTP_USER_NAME}
        - SMTP_PASSWORD=${SMTP_PASSWORD}
        - SMTP_HOST=${SMTP_HOST}
        - SMTP_PORT=${SMTP_PORT}
        - SMTP_SECURITY=${SMTP_SECURITY}
        - SMTP_TO=${SMTP_TO}
        - SMTP_FROM=${SMTP_FROM}
    volumes:
      - ./isso/db:/isso/db
      - ./isso/log:/isso/log

  nginx:
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  /etc/letsencrypt:
    external: true

