version: "3"

services:
  ghost:
    image: ghost:alpine
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - url=${DEV_HOST}
    volumes:
      - ./ghost/content:/var/lib/ghost/content
      - ./ghost/config.production.json:/var/lib/ghost/config.production.json
      - ./ghost/config.development.json:/var/lib/ghost/config.development.json

  isso:
    build:
      context: ./isso
      dockerfile: Dockerfile
      args:
        - DEV_HOST=${DEV_HOST}
        - ISSO_HOST=${ISSO_HOST}
        - ISSO_PORT=${ISSO_PORT}
        - SMTP_USER_NAME=${SMTP_USER_NAME}
        - SMTP_PASSWORD=${SMTP_PASSWORD}
        - SMTP_HOST=${SMTP_HOST}
        - SMTP_PORT=${SMTP_PORT}
        - SMTP_SECURITY=${SMTP_SECURITY}
        - SMTP_TO=${SMTP_TO}
        - SMTP_FROM=${SMTP_FROM}
    restart: unless-stopped
    volumes:
      - ./isso/db:/isso/db
      - ./isso/log:/isso/log


  nginx:
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - ${DEV_HOST_PORT}:${DEV_CONTAINER_PORT}