version: "3"

services:
  ghost:
    image: ghost:alpine
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - url=${PRO_HOST}
    volumes:
      - ./ghost/content:/var/lib/ghost/content
      - ./ghost/config.production.json:/var/lib/ghost/config.production.json
      - ./ghost/config.development.json:/var/lib/ghost/config.development.json

  isso:
    build:
      context: ./isso
      dockerfile: Dockerfile
      args:
        - PRO_HOST=${PRO_HOST}
        - ISSO_HOST=${ISSO_HOST}
        - ISSO_PORT=${ISSO_PORT}
        - SMTP_USER_NAME=${SMTP_USER_NAME}
        - SMTP_PASSWORD=${SMTP_PASSWORD}
        - SMTP_HOST=${SMTP_HOST}
        - SMTP_PORT=${SMTP_PORT}
        - SMTP_SECURITY=${SMTP_SECURITY}
        - SMTP_TO=${SMTP_TO}
        - SMTP_FROM=${SMTP_FROM}
    restart: unless-stopped
    volumes:
      - ./isso/db:/isso/db
      - ./isso/log:/isso/log


  nginx:
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - ${PRO_HOST_PORT}:${PRO_CONTAINER_PORT}
    volumes:
      - /etc/letsencrypt/live/nendo.co/fullchain.pem:/etc/letsencrypt/live/${PRO_HOST_DOMAIN}/fullchain.pem
      - /etc/letsencrypt/live/nendo.co/privkey.pem:/etc/letsencrypt/live/${PRO_HOST_DOMAIN}/privkey.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem



