# version: "3"

# services:
#   ghost:
#     image: ghost:alpine
#     restart: unless-stopped
#     ports:
#       - 2368:2368
#     volumes:
#       - ./ghost/content:/var/lib/ghost/content
#       - ./ghost/config.production.json:/var/lib/ghost/config.production.json
#       - ./ghost/config.development.json:/var/lib/ghost/config.development.json
#   isso:
#     build: ./isso
#     volumes:
#       - ./isso/db:/isso/db
#     ports:
#       - 8080:8080
#     environment:
#       $HOST: 127.0.0.1
#       $ISSO_PORT: 8080
#       $SMTP_USER_NAME: ''
#       $SMTP_PASSWORD: ''
#       $SMTP_HOST: 127.0.0.1
#       $SMTP_PORT: 2500
#       $SMTP_SECURITY: ''
#       $SMTP_TO: test@test.com
#       $SMTP_FROM: test@test.com