version: "3"

services:
  ghost:
    image: ghost:alpine
    restart: unless-stopped
    environment:
      - NODE_ENV
      # - url=https://nendo.ml
      - url=http://localhost:2368
    volumes:
      - ./ghost/content:/var/lib/ghost/content
      - ./ghost/config.production.json:/var/lib/ghost/config.production.json
      - ./ghost/config.development.json:/var/lib/ghost/config.development.json

  isso:
    build:
      context: ./isso
      dockerfile: Dockerfile
      args:
        - HOST=${HOST}
        - ISSO_HOST=${ISSO_HOST}
        - ISSO_PORT=${ISSO_PORT}
        - SMTP_USER_NAME=${SMTP_USER_NAME}
        - SMTP_PASSWORD=${SMTP_PASSWORD}
        - SMTP_HOST=${SMTP_HOST}
        - SMTP_PORT=${SMTP_PORT}
        - SMTP_SECURITY=${SMTP_SECURITY}
        - SMTP_TO=${SMTP_TO}
        - SMTP_FROM=${SMTP_FROM}
    restart: unless-stopped
    volumes:
      - ./isso/db:/isso/db
      - ./isso/log:/isso/log


  nginx:
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      # - 80:80
      - 443:443
    # volumes:
    #   - /etc/letsencrypt/live/nendo.ml/fullchain.pem:/etc/letsencrypt/live/nendo.ml/fullchain.pem
    #   - /etc/letsencrypt/live/nendo.ml/privkey.pem:/etc/letsencrypt/live/nendo.ml/privkey.pem
    #   - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
    #   - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem



